//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace isaretleharita
{
    using System;
    using System.Collections.Generic;
    
    public partial class maps
    {
        public int id { get; set; }
        public string lat { get; set; }
        public string lng { get; set; }
        public string comment { get; set; }
    }
}
